# FINM3422 – Lecture 5 In‑Class Notebook (Foundations)
Use this during the lecture. Cells marked **TODO (lecture)** are completed live in class.

In [ ]:

%pip install --upgrade pip
%pip install pandas
%pip install matplotlib

In [1]:
# 0) Sanity check: Python, pandas, matplotlib
print('Hello FINM3422 👋')
import sys, pandas as pd, matplotlib.pyplot as plt
sys.version.split()[0]

Hello FINM3422 👋

'3.14.3'

## 1) Load data (prices, monthly)
We keep a tiny CSV in `data/prices_monthly.csv` with a `Date` column and a few asset columns.

In [2]:
# TODO (lecture): Run the following code : Create a DataFrame of stock prices for two stocks A and B:
prices = pd.DataFrame({'A':[100,101,103],'B':[100,99,100]}, index=pd.to_datetime(['2020-01-31','2020-02-29','2020-03-31']))
prices.head()

              A    B
2020-01-31  100  100
2020-02-29  101   99
2020-03-31  103  100

In [3]:
# TODO (lecture): read the CSV so that Date becomes the index and is parsed as datetime
# Hints: use pd.read_csv('filename.csv', parse_dates=['Date'], index_col='Date')
# Replace the placeholder below.
import pandas as pd
#placeholder for pd.read_csv
prices.head()

              A    B
2020-01-31  100  100
2020-02-29  101   99
2020-03-31  103  100

## 2) Inspect quickly
Use `.info()`, `.head()`, and `.describe()` to build trust in the table before modelling.

In [4]:
prices.info()
display(prices.head())
display(prices.describe())

<class 'pandas.DataFrame'>
DatetimeIndex: 3 entries, 2020-01-31 to 2020-03-31
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 72.0 bytes

              A    B
2020-01-31  100  100
2020-02-29  101   99
2020-03-31  103  100

                A           B
count    3.000000    3.000000
mean   101.333333   99.666667
std      1.527525    0.577350
min    100.000000   99.000000
25%    100.500000   99.500000
50%    101.000000  100.000000
75%    102.000000  100.000000
max    103.000000  100.000000

## 3) Compute simple returns
We want fractional monthly returns from prices.

In [ ]:
# TODO (lecture): fill in pct_change to compute returns
# returns = prices.____().dropna()
returns.head()

## 4) Ensure monthly labels
Label the index monthly (no aggregation).

In [ ]:
# TODO (lecture): use asfreq to set a monthly frequency label
# returns = returns.____('ME')
returns.index.freq

## 5) Wealth index & one plot
From returns to an indexed wealth curve (start = 1.0).

In [ ]:
# TODO (lecture): complete the one-liner for wealth index
import matplotlib.pyplot as plt
# wealth = (1 + returns).____().cumprod()
ax = wealth.plot(title='Wealth index (start=1.0)')
ax.set_xlabel('Date'); ax.set_ylabel('Index'); plt.show()

## 6) Stretch: handle missing values (choose & document)
Decide whether to `ffill`, `bfill`, or `dropna`, and *state why*.

In [ ]:
# OPTIONAL TODO (lecture/tutorial): experiment with missing-data handling
returns_clean = returns.dropna()
returns_clean.head()

## 7) Save figure (optional)
Saving outputs makes your work reproducible.

In [ ]:
# OPTIONAL: save plot
import os
os.makedirs('outputs', exist_ok=True)
ax = wealth.plot(title='Wealth index (saved)')
plt.savefig('outputs/wealth_index.png', dpi=150); plt.close()
'Saved to outputs/wealth_index.png'